spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: circuit-breaker
  profiles:
    active: dev

server:
  port: 4000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

resilience4j:
  retry:
    instances:
      get-message:
        maxAttempts: 2
        waitDuration: 1000