apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  labels:
    app: hello-world
  name: hello-world
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - image: muratcanabay/hello-world:0.0.2-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: hello-world
#          env:
#            - name: HELLO_WORLD
#              value: "Hello from the environment"
          envFrom:
            - configMapRef:
                name: hello-world-configmap
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: hello-world
  name: hello-world
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: hello-world
  sessionAffinity: None
  type: LoadBalancer
