apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: "2022-05-29T14:45:31Z"
  generation: 5
  labels:
    app: hello-world
  name: hello-world
  namespace: default
  resourceVersion: "667938"
  uid: 7ab3040a-d004-4425-88d4-2b0e01e46f7d
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello-world
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-world
    spec:
      containers:
        - image: muratcanabay/hello-world:0.0.2-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: hello-world
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
    - lastTransitionTime: "2022-05-29T19:56:08Z"
      lastUpdateTime: "2022-05-29T19:56:08Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-05-29T14:45:31Z"
      lastUpdateTime: "2022-05-30T19:48:35Z"
      message: ReplicaSet "hello-world-74c455bf77" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 5
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
