spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: currency-conversion-service
  profiles:
    active: dev

server:
  port: 3000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true