spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: eureka-server
  profiles:
    active: dev

server:
  port: 8761

# means: do not register itself
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false