spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: currency-exchange-service
  profiles:
    active: dev

  # h2 properties
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    # to start with data.sql data
    defer-datasource-initialization: true
  # h2 default random database name like: jdbc:h2:mem:adff70e6-84e6-4b86-8ec7-e1df22f3386d
  datasource:
    url: jdbc:h2:mem:currency-exchange

server:
  port: 2000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/