server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/murat/Desktop/dev/spring-microservice-example/git-config-repo
          default-label: main